language: rust

before_script:
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview
matrix:
  include:
  - rust: 1.30.0
  - rust: stable
  - rust: beta
  - rust: nightly
    env: ALLOW_FAILURES=true
  - os: osx
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=x86_64-unknown-linux-gnu
script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
