[workspace]
members = [
    "lambda-runtime-client",
    "lambda-runtime",
    "lambda-http",
    "lambda-runtime-client-simple"
]

[patch.crates-io]
tower-service = { git = "https://github.com/tower-rs/tower" }
