[package]
name = "lambda"
version = "0.1.0"
authors = ["David Barsky <dbarsky@amazon.com>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
tokio = { version = "0.2.4", features = ["full"] }
hyper = { git = "https://github.com/hyperium/hyper" }
async-stream = "0.2"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
serde_json = "1.0.39"
tower-service = "0.3"
bytes = "0.5"
http = "0.2"
headers = { git = "https://github.com/hyperium/headers" }
lazy_static = "1.3.0"
proptest = { git = "https://github.com/davidbarsky/proptest" }
proptest-attributes = { git = "https://github.com/davidbarsky/proptest" }
lambda-attributes = { path = "../lambda-attributes", version = "0.1.0" }
