[package]
name = "simple-lambda-runtime"
version = "0.1.0"
authors = ["David Barsky <dbarsky@amazon.com>"]
edition = "2018"

[dependencies]
bytes = "^0.4"
failure = "^0.1"
futures = "^0.1"
hyper = "^0.12"
http = "^0.1"
tokio = "^0.1"
tower-service = { version = "0.2", git = "https://github.com/tower-rs/tower.git" }
tower-retry = { version = "0.1", git = "https://github.com/tower-rs/tower.git" }
tower-timeout = { version = "0.1", git = "https://github.com/tower-rs/tower.git" }
tower-util = { version = "0.1", git = "https://github.com/tower-rs/tower.git" }
serde = { version = "^1", feature = ["derive"] }
serde_json = "^1"

[patch.crates-io]
http = { git = "https://github.com/hyperium/http" }