[package]
name = "simple-lambda-runtime"
version = "0.1.0"
authors = ["David Barsky <dbarsky@amazon.com>"]
edition = "2018"

[dependencies]
bytes = "^0.4"
failure = "^0.1"
futures = "^0.1"
hyper = "^0.12"
http = "^0.1"
tokio = "^0.1"
tower-service = "^0.2"
serde = { version = "^1", feature = ["derive"] }
serde_json = "^1"
